[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65AD59990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65AD5A650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65AD5B310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B6A4490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B6A4C90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B6A5C90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5