[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B6A4710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B575310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B5755D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B302010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B302490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F65B301CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c780a31aafa1cafb1c9ca2a85e3798d5